/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/house.ts
 * Command: astryx theme build theme/house.ts --out theme/house.css
 * Generated: 2026-08-16T12:24:55.118Z
 */

/// <reference path="./house.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const houseTheme: DefinedTheme;
